FROM tomcat:8
MAINTAINER "Jeff Heath <jeff.heath@clearavenue.com>"
## Uncomment these two commented ADD lines and edit the included
## settings.xml and tomcat-user.xml if you have need to use the
## Tomcat 8 management GUI
#ADD settings.xml /usr/local/tomcat/conf/
#ADD tomcat-users.xml /usr/local/tomcat/conf/
ADD FDADI.war /usr/local/tomcat/webapps/
